language: cpp
os: windows

install:
    choco install visualstudio2017-workload-vctools -y
    
script:
    - dir
    - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" x64
    - cl.exe







