language: cpp
os: windows

before_install:
    - curl -sL https://gitlab.com/libeigen/eigen/-/archive/3.3.7/eigen-3.3.7.zip > eigen-3.3.7.zip
    
install:
    - choco install make -y
    - choco install visualstudio2017-workload-vctools -y
    - choco install opencv --version=3.4.7 -params '/InstallationPath:C:\tools' -y
    - 7z x eigen-3.3.7.zip -o"C:\tools"
    
env:
    - INCLUDES="-IC:\tools\eigen-3.3.7 -IC:\tools\opencv"
    
script:
    - echo $INCLUDES
    - cd C:\tools
    - dir
    - cd $TRAVIS_BUILD_DIR
    - dir test\main.cpp
    - mkdir build\test\bin
    - cd build\test\bin
    - cmd.exe //C 'C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Auxiliary\Build\vcvarsall.bat' amd64 '&&' cl.exe '..\..\..\test\main.cpp' $INCLUDES /EHsc /Fetests.exe
    