language: cpp
os: windows

install:
    choco install visualstudio2017-workload-vctools -y
    
script:
    - dir
    - mkdir build\\test\\bin
    - cmd.exe //C 'C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Auxiliary\Build\vcvarsall.bat' amd64 '&&' cd build\\test\\bin '&&' dir
    







