language: cpp
os: windows

install:
    - curl https://gitlab.com/libeigen/eigen/-/archive/3.3.7/eigen-3.3.7.zip
    

install:
    - choco install visualstudio2017-workload-vctools -y
    - choco install opencv -y
    
script:
    - dir
    - mkdir build\test\bin
    - cmd.exe //C 'C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Auxiliary\Build\vcvarsall.bat' amd64 '&&' cd build\test\bin '&&' cl.exe
    







